#!/usr/bin/env python

import argparse
import json
import os
import requests
import sys
import time

parser = argparse.ArgumentParser(description='Get ZooKeeper Connect configuration by querying Consul.')
parser.add_argument('brokerid', type=int, help='brokerid')
args = parser.parse_args()

consul_http_addr = os.getenv('CONSUL_HTTP_ADDR', 'consul:8500')
if int(args.brokerid) <= 0:
    print(f"[ERR] Unknown Broker ID {args.brokerid}.", file=sys.stderr)
    exit(1)

for attempt in range(4):
    try:
        r = requests.get(f"http://{consul_http_addr}/v1/catalog/service/kafka?tag=brokerid%3D{args.brokerid}")
        r.raise_for_status()
        res = r.json()
        if len(res) > 0:
            print(json.dumps(res[0]))
            exit(0)
        else:
            time.sleep(2 ** attempt)
    except requests.exceptions.RequestException as e:
        time.sleep(2 ** attempt)
print("")
exit(0)
