#!/usr/bin/env python

import argparse
import os
import requests

parser = argparse.ArgumentParser(description='Get ZooKeeper Connect configuration by querying Consul.')

args = parser.parse_args()

consul_http_addr = os.getenv('CONSUL_HTTP_ADDR', 'consul:8500')
try:
    r = requests.get(f"http://{consul_http_addr}/v1/catalog/service/zookeeper-2181")
    r.raise_for_status()
    print(",".join([f"{node['ServiceAddress']}:{node['ServicePort']}" for node in r.json()]))
    exit(0)
except requests.exceptions.RequestException as e:
    print("")
    exit(0)
